### ISSUE TITLE
看起来很不错

### ISSUE THREAD

**Issue by mujiannan** [linkedin/Li-Airflow-Backfill-Plugin#3]
现在原生airflow的缺点是批量补任务需要调api或进后台，尤其k8s部署时控制台权限是一个很大的管理麻烦。Catchup可控性又比较差。  

期待哪天原生出手给这儿来一下：
![image](https://github.com/linkedin/Li-Airflow-Backfill-Plugin/assets/46643837/ab914159-bacb-41f1-97c2-63f835205d4c)

这样你就白干了🤣

**Comment by zhuowang10** [comment]
这样可以解决一部分问题，但不能解决backfill运行时会block scheduled run的问题，也无法分别控制max active run
